<a href="https://colab.research.google.com/github/tshiven/Codemy_Pytorch/blob/main/Codemy_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

Tensors - similar to numpy arrays but more suitable for GPUs and have default data type of float32.

In [3]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.0566, 0.4106, 0.2840, 0.9419],
        [0.9789, 0.6041, 0.6678, 0.7388],
        [0.6238, 0.1850, 0.3646, 0.3701]])

In [4]:
tensor_3d = torch.ones(3,4,1)
tensor_3d

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])

In [5]:
np1 = np.random.rand(3,4) #in random.rand, u don't need tuple unlike others like ones
np1

array([[0.52256288, 0.3028915 , 0.54645351, 0.48880522],
       [0.37334295, 0.92827455, 0.89123721, 0.24367593],
       [0.93320973, 0.77820064, 0.6714213 , 0.16045043]])

In [6]:
my_tensor = torch.tensor(np1) #gets dtype from np
my_tensor

tensor([[0.5226, 0.3029, 0.5465, 0.4888],
        [0.3733, 0.9283, 0.8912, 0.2437],
        [0.9332, 0.7782, 0.6714, 0.1605]], dtype=torch.float64)

In [7]:
my_tensor = torch.arange(-5,5,1)
my_tensor

tensor([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [8]:
my_tensor.reshape(2,-1) #for one dimension

tensor([[-5, -4, -3, -2, -1],
        [ 0,  1,  2,  3,  4]])

In [9]:
#View and reshape are very similar except they differ when it comes to contiguity.
#Transposing or slicing makes it uncontigous

#Building a simple neural network

In [10]:
import torch.nn as nn #importing a neural network
import torch.nn.functional as F

In [11]:
#Create a model clas that inherits nn.Module
class Model(nn.Module):
  #Input Layer(4 features of the flower). --> H1 --> H2 --> Output(3 classes of iris)
  def __init__(self, in_features = 4, h1 = 8, h2 = 9, out_features =3):
    super().__init__() #runs our nn.Module
    self.fc1 = nn.Linear(in_features,h1) #fc is fully connected (like a neutron), linear represents a linear transformation
    self.fc2 = nn.Linear(h1,h2)
    self.out = nn.Linear(h2,out_features)

  def forward(self, x):
    #basically it goes through each layer
    x = F.relu(self.fc1(x)) #if its less than 0, it becomes 0 otherwise it is the value given
    x = F.relu(self.fc2(x))
    x = F.relu(self.out(x))
    return x

In [12]:
#Giving it a manual seed so that u get somewhat specific random numbers
torch.manual_seed(41)

#Create an instance of our model
model = Model()

#Importing our dataset

In [13]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
url = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
df = pd.read_csv(url)

In [15]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [16]:
df.tail() #gives last 5 instances while .head() gives first 5

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [27]:
df['species'] = df['species'].replace('setosa',0)     #replacing last column with codes for ML
df['species'] = df['species'].replace('versicolor',1)
df['species'] = df['species'].replace('virginica',2)
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2      0.0
1             4.9          3.0           1.4          0.2      0.0
2             4.7          3.2           1.3          0.2      0.0
3             4.6          3.1           1.5          0.2      0.0
4             5.0          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [18]:
#Train test split! Set X,y
#.drop removes certain columns, axes etc.

X = df.drop('species', axis = 1) #drops the species columns in axis 1 since we want to predict species
y = df['species'] #y is the species now

In [19]:
X = X.values
y = y.values

In [20]:
y #number for species

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [21]:
from sklearn.model_selection import train_test_split # this helps split data into train and test for ML

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 41) #20% - testing data, 80% - training data random_state for similar randomization

In [23]:
#Convert X features to float tensors
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

In [24]:
#Convert Y features to long tensors
y_train = torch.LongTensor(y_train) #We want integers
y_test = torch.LongTensor(y_test)

In [28]:
#Set the criterion of model to measure the error, how far we r from reality..its like error calculation
criterion = nn.crossEntropyLoss()

#Choose Adam Optimizer, learning rate()

AttributeError: module 'torch.nn' has no attribute 'CrossEnt'